version: "3"

services:
  magicmerchant-backend:
    build:
      context: ./backend
    container_name: magicmerchant-backend
    environment:
      #- MAGIC_API_KEY=f00d0934--wa7M-pDSHGW5bHg_LM3srn1GRbnZMmJE1OQZ6RcAaIuvuLxbShcm9-6vt7me_6kZyVYmBemdK590lQfwBQSl3JE4U-9Vg
      - MAGIC_API_KEY=f2d0761c-elNiI4dRkEtZ_5vRWsixgBfNdmLTHvib31QV3gavlozLv_zKREZGgzk3-j4eFUuJiTk0cxBAKyqnXNEWew1bOTZyL_YJDA
      - MAGIC_URL=https://api-sandbox.join-magic.com
    volumes:
      - ./backend:/app
    ports:
      - "4005:4005"
    networks:
      - magic_merchant_net

  magicmerchant-frontend:
    build:
      context: ./frontend
    ports:
      - "3003:3000"
    container_name: magicmerchant-frontend
    stdin_open: true
    volumes:
      - ./frontend:/frontend
    depends_on:
      - magicmerchant-backend
    networks:
      - magic_merchant_net

networks:
  magic_merchant_net:
    external:
      name: "magic_merchant_net"
