# Generated by Django 4.2.6 on 2023-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('checkout_id', models.CharField(max_length=20)),
                ('link_token', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=20)),
            ],
        ),
    ]
